# seedBank example configuration created by Jasper Poppe <jpoppe@ebay.com>
#
# hint: all settings could be overridden by creating override yaml files
# in the configs directory (default: /etc/seedbank/configs)

# when the seedBank daemon is used it should be restarted after changing
# those settings (/etc/init.d/seedbank restart)
# seed_host -> used as variable in other settings
settings:
  seed_host: 192.168.0.1
  bottle_listen: ''
  bottle_port: '7467'
  bottle_server: WSGIRefServer
  #bottle_server: FlupFCGIServer
  configuration_path: /etc/seedbank/conf.d
