seed:
  add_kernel_opts: ''
  debian_mirrorhostname: 192.168.0.1
  debian_mirrordirectory: /debian/mirror
  ntp_server: ntp.xs4all.nl
  timezone: Europe/Amsterdam
  country+chooser: NL
  locale: en_US
